const config = {
    preamble_url:  ("https://constitution.congress.gov/constitution/article-1/"),
    article_I_url: ("https://constitution.congress.gov/constitution/article-1/"),
    article_II_url: ("https://constitution.congress.gov/constitution/article-2/"),
    article_III_url: ("https://constitution.congress.gov/constitution/article-3/"),
    article_IV_url: ("https://constitution.congress.gov/constitution/article-4/"),
    article_V_url: ("https://constitution.congress.gov/constitution/article-5/"),
    article_VI_url: ("https://constitution.congress.gov/constitution/article-6/"),
    article_VII_url: ("https://constitution.congress.gov/constitution/article-7/"),
    first_amendment_url: ("https://constitution.congress.gov/constitution/amendment-1/"),
    second_amendment_url: ("https://constitution.congress.gov/constitution/amendment-2/"),
    third_amendment_url: ("https://constitution.congress.gov/constitution/amendment-3/"),
    fourth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-4/"),
    fifth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-5/"),
    sixth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-6/"),
    seventh_amendment_url: ("https://constitution.congress.gov/constitution/amendment-7/"),
    eighth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-8/"),
    ninth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-9/"),
    tenth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-10/"),
    eleventh_amendment_url: ("https://constitution.congress.gov/constitution/amendment-11/"),
    twelfth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-12/"),
    thirteenth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-13/"),
    fourteenth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-14/"),
    fifteenth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-15/"),
    sixteenth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-16/"),
    seventeenth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-17/"),
    eighteenth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-18/"),
    nineteenth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-19/"),
    twentieth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-20/"),
    twenty_first_amendment_url: ("https://constitution.congress.gov/constitution/amendment-21/"),
    twenty_second_amendment_url: ("https://constitution.congress.gov/constitution/amendment-22/"),
    twenty_third_amendment_url: ("https://constitution.congress.gov/constitution/amendment-23/"),
    twenty_fourth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-24/"),
    twenty_fifth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-25/"),
    twenty_sixth_amendment_url: ("https://constitution.congress.gov/constitution/amendment-26/"),
    twenty_seventh_amendment_url: ("https://constitution.congress.gov/constitution/amendment-27/")
};
export default config;
